name: belaaraby
description: A new Flutter project.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.1+3
environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: any
  firebase_core: ^1.12.0
  firebase_auth: ^3.3.6
  firebase_storage: ^10.2.7
  firebase_analytics: ^9.1.0
  firebase_database: ^9.0.14
  google_sign_in: ^5.3.3

  badges: ^2.0.3
  google_maps_flutter: ^2.1.8
  #google_maps_flutter:
  #  git:
    #  url: git://github.com/klausjokinen/plugins/
   #   path: packages/google_maps_flutter
  #    ref: map_keepAlive
  geolocator: ^8.2.1
  flutter_map: any
  #location: ^4.2.0
  #latlong: ^0.6.1
  carousel_slider: ^4.1.1
  http: ^0.13.4
  shared_preferences: ^2.0.15
  fluttertoast: ^8.0.8
  geocoding: ^2.0.2
  geocode: ^1.0.1
  flutter_map_marker_cluster: ^0.4.4
  syncfusion_flutter_maps: ^20.1.58
  map_launcher: ^2.1.2
  flutter_svg: # only if you want to use icons as they are svgs
  # country_state_city_picker: ^1.2.8
  intl_phone_number_input: ^0.7.0+2
  awesome_dialog: ^2.2.1
  animated_button: ^0.2.0
  bottom_sheet: ^3.1.1
  expandable_bottom_bar: ^2.0.2
  url_launcher: ^6.0.20
  image_picker: ^0.8.4+8
  file_picker: ^4.4.0
  image: ^3.1.3
  images_picker: ^1.2.10
  dio: ^4.0.4
  multi_image_picker: ^4.8.1
  day_night_time_picker: ^1.0.5
  google_fonts: ^3.0.1
  charts_flutter: ^0.12.0
  csc_picker: ^0.2.6
  rating_dialog: ^2.0.3
  path_provider: ^2.0.9
  uuid: 3.0.6
  loading_indicator: ^3.1.0
  animated_text_kit: any
  intl: any
  flutter_rating_bar: ^4.0.1
  get: any
  pinch_zoom: ^1.0.0
  font_awesome_flutter: ^10.1.0
  ionicons: ^0.1.2
  #flutter_xlider: any
  location: any
  #flutter_cache_manager: ^3.3.0
  marker_icon: ^0.7.1
  custom_map_markers: ^0.0.1
  dropdown_button2: ^1.6.3
  flutter_easyloading: any
  date_format: any
  youtube_player_flutter: ^8.1.0
  settings_ui: ^2.0.2
  #search
  #flutter_search_bar: ^2.1.0
  anim_search_bar: ^2.0.2
  easy_search_bar: ^2.3.1
  flutter_typeahead: ^4.0.0
  flutter_native_splash: any
  responsive_sizer: ^3.1.0
  flutter_screenutil: any
  tutorial_coach_mark: ^1.2.4

  selectable: ^0.2.3
  flutter_automation: ^2.0.0
  change_app_package_name: ^1.1.0


  cupertino_icons: ^1.0.2

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/appLogo.png"

dev_dependencies:
  flutter_launcher_icons: "^0.9.2"

  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

module:
  androidX: true # Add this line.
flutter:


  uses-material-design: true

  assets:
    - assets/
    - assets/jobType/
    - assets/map_styles/

flutter_native_splash:
  color: "#0a1227"
  image: assets/splashLogo.png
  fullscreen: true
  andoid: true
  ios: true
  # android_disable_fullscreen: true